### ISSUE TITLE
SignUp view, nothing happening 

### ISSUE THREAD

**Issue by sergeifedorenko** [easably/context-tutor#14] opened 2019-02-18 08:24 UTC
![image](https://user-images.githubusercontent.com/5947223/52937172-72af7a80-336f-11e9-8c63-18d81fc4f644.png)

**Comment by BelkevichAndry** [comment] 2019-02-18 13:16
@sergeifedorenko @marysergey, the problem was with password validation, we need to add custom message like "Password should contain at least 6 characters..". As you can see from screen, now we just show "red line" after password input and do not allow user to sign up

**Comment by marysergey** [comment] 2019-02-22 08:12
@sergeifedorenko @BelkevichAndry 
I think the problem is not fixed because I see this information.
   I could not log in by password recovery too
![default](https://user-images.githubusercontent.com/47523695/53228581-ae5d8380-3692-11e9-994b-870870710fab.jpg)
![2](https://user-images.githubusercontent.com/47523695/53228582-ae5d8380-3692-11e9-9d9c-235ebef5f93d.jpg)

**Comment by ErgerSusha** [comment] 2019-08-30 09:33
Login behavior was greatly changed since this issue was opened. Closing issue for now.

**Closed by ErgerSusha** 2019-08-30 09:33 UTC
Labels: high
