### ISSUE TITLE
"Share" and Sign In form

### ISSUE THREAD

**Issue by alla-cherniauskaya** [easably/context-tutor#46] opened 2019-06-04 14:08 UTC
I wanted to Share some sentences from another app to EasyLang. This window appeared is good, but...

![Screenshot_2019-06-04-16-40-02-404_app easylang](https://user-images.githubusercontent.com/47523071/58885164-60710680-86ea-11e9-9570-563793c38506.png)

...when I decided back to All Lessons window tapping the arrow at the top left angle,  I ended up on Sign in form. After repeated Sign in, I returned to the window on the previous screenshot and can't back to the main window with lessons.

![Screenshot_2019-06-04-16-39-57-231_app easylang](https://user-images.githubusercontent.com/47523071/58885174-67981480-86ea-11e9-8524-058e5474dafa.png)

**Comment by ErgerSusha** [comment] 2019-06-06 07:25
Back button behavior was changed by 9e0b926. Now it resets shared sentence and goes to lessons list page.

**Comment by alla-cherniauskaya** [comment] 2019-06-07 10:20
There's still a bug

**Comment by ErgerSusha** [comment] 2019-08-30 09:22
Just tested this issue and it seems to work as intended. Closing issue for now.

**Closed by ErgerSusha** 2019-08-30 09:22 UTC
Labels: Task, bug
